In [2]:
import requests
import pandas as pd
import numpy as np
from pandas import json_normalize

In [3]:
response = requests.get('https://api.sportsdata.io/v3/nfl/scores/json/TeamSeasonStats/2020REG?key=d8b5ea01537141eb9a320f95994b7109')

In [4]:
df = pd.DataFrame.from_dict(response.json())

In [10]:
df.head()
df['average_score'] = round((df['Score'] / df['Games']), 2)

In [11]:
df.head()

,SeasonType,Season,Team,Score,OpponentScore,TotalScore,Temperature,Humidity,WindSpeed,OverUnder,...,Games,PassingDropbacks,OpponentPassingDropbacks,TeamSeasonID,TwoPointConversionReturns,OpponentTwoPointConversionReturns,TeamID,GlobalTeamID,TeamStatID,average_score
0,1,2020,ARI,234,180,414,82,81,9,55.8,...,8,314,349,201000001,0,0,1,1,201000001,29.25
1,1,2020,ATL,243,251,494,73,66,11,56.8,...,9,404,397,201000002,0,0,2,2,201000002,27.00
2,1,2020,BAL,227,142,369,71,77,11,52.3,...,8,258,361,201000036,0,0,3,3,201000036,28.38
3,1,2020,BUF,242,233,475,70,72,8,51.9,...,9,370,354,201000037,0,0,4,4,201000037,26.89
4,1,2020,CAR,210,226,436,73,59,9,53.5,...,9,358,372,201000005,0,0,5,5,201000005,23.33